version: '3.4'
services:
  netbox:
    ports:
    - 8080:8080
    volumes:
    - ./etc/netbox/config:/netbox
    - netbox-media-files:/opt/netbox/netbox/media
    - netbox-reports-files:/mnt/netbox/reports
    - netbox-scripts-files:/mnt/netbox/scripts
    healthcheck:
      retries: 15
  netbox-worker:
    volumes:
    - ./etc/netbox/config:/netbox
    - netbox-media-files:/opt/netbox/netbox/media
    - netbox-reports-files:/mnt/netbox/reports
    - netbox-scripts-files:/mnt/netbox/scripts
  netbox-housekeeping:
    volumes:
    - ./etc/netbox/config:/netbox
    - netbox-media-files:/opt/netbox/netbox/media
    - netbox-reports-files:/mnt/netbox/reports
    - netbox-scripts-files:/mnt/netbox/scripts
